#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Remove the default Nginx site configuration from sites-enabled
sudo rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default Nginx site configuration in sites-enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the configuration changes
sudo service nginx restart
