#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Create a symbolic link to the default Nginx site configuration in sites-enabled,
# overwriting it if it already exists
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start the Nginx service to apply the new configuration
sudo service nginx start

# Kill the first Nginx process to force a restart with the updated configuration
sudo kill "$(pgrep 'nginx' | head -1)"