#!/usr/bin/env bash
# Purpose: Displays "To infinity and beyond" indefinitely, and reacts to SIGTERM signal.

trap "echo 'I am invincible!!!'" SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
