#!/usr/bin/env bash
# Purpose: Displays a story with information from each line of /etc/passwd.

input="/etc/passwd"
while IFS=: read -r username password userid groupid userINFO homedir shell
do
    echo "The user $username is part of the $groupid gang, lives in $userINFO, and rides $homedir:$shell. $userid's place is protected by the passcode $password. More info about the user here: $userINFO"
done < "$input"
