#!/usr/bin/env bash
# Purpose: Displays a story with information from each line of /etc/passwd.

input="/etc/passwd"
while IFS=: read -r username password userID groupID userINFO homeDIR shell
do
    echo "The user $username is part of the $groupID gang, lives in $homeDIR and rides $shell. $userID's place is protected by the passcode $password, more info about the user here: $userINFO"
done < "$input"
