#!/usr/bin/env bash
# Purpose: Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash.

for file in *; do
  if [[ -f $file ]]; then
    cut -d '-' -f2 <<< "$file"
  fi
done
