#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports:
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)
echo -e "Updating\n"
sudo apt-get -y update

echo -e "Installing ufw\n"
sudo apt-get -y install ufw

echo -e "configuring ufw...\n"
# Allow Outgoing and Deny Incoming
sudo ufw default allow outgoing
sudo ufw default deny incoming
# Allow ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
# Enable Fire Wall
sudo ufw enable

echo -e "Process Completed.\n"
