#!/usr/bin/env bash
# Purpose: Changes localhost to 127.0.0.2 and facebook.com to 8.8.8.8 in /etc/hosts.

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
